{
    "name" : "carpetas",
    "version" : "1.0",
    "author" : "Datamatic",
    "website" : "www.datamatic.com.uy",
    "category" : "carpetas",
    "description": """ Gestion de Carpetas """,
    "depends" : ['expedientescarpetas'],
    "init_xml" : ['datosiniciales.xml'],
    "demo_xml" : [],
    "update_xml" : ['carpeta_view.xml',
                   'conceptocarpetas_view.xml',
                   'notas_view.xml',
                   'partner_view.xml'],                    
    "installable": True,
    "active": False,      
}