
{
    "name" : "dtm_inmobiliaria",
    "version" : "1.0",
    "author" : "Datamatic",
    "website" : "www.datamatic.com.uy",
    "category" : "Inmobiliarias",
    "description": "Gestión de Inmobiliarias",
    "depends" : ['base','crm_claim','project','account','document'],
    "init_xml" : ['security/estate_security.xml',
                 'security/inmobiliaria_security.xml'],
    "demo_xml" : [],
    "update_xml" : [
                    'estate_view.xml',
                    'partner_view.xml',
                    'report/estate_report.xml',
                    'crm_lead_view.xml',
                    'pedidos.xml',
                    'pedidos_clientes_view.xml',
                    'security/inmobiliaria_security.xml',
                    'security/ir.model.access.csv',
                    'data/departamentos_uy.xml',
                    'data/paises.xml',
                    'data/tipo_inmueble.xml',
                    'data/estado_inmueble.xml',
                    'data/ubicacion_propiedad.xml',

                    ],
    "installable": True,
    "active": False,
    }
