{
    "name" : "expedientes",
    "version" : "1.0",
    "author" : "Datamatic",
    "website" : "www.datamatic.com.uy",
    "category" : "expedientes",
    "description": """ Gestion de Expedientes """,
    "depends" : ['expedientescarpetas'],
    "init_xml" : ['datosiniciales.xml'],
    "demo_xml" : [],
    "update_xml" : ['expedientes_view.xml',
		      'consulta_expediente_view.xml',
                    'conceptosdocumentos_view.xml',
                    'notas_view.xml','poderjudicial_view.xml',
                    'juzgado_view.xml',
                    'partner_view.xml',
                    'organismo_view.xml',
                    'crm_meeting_view.xml',
                    'horas_view.xml',
                    'report/report_print_report.xml'
		     ],                    
    "installable": True,
    "active": False,      
}